### ISSUE TITLE
add support for optional types

### ISSUE THREAD

**Issue by nadavbarlev** [pitt500/SwiftAndTipsMacros#2]
Currently, when using the macro on a struct with a member of an optional type, like -

```
@SampleBuilder(numberOfItems: 10, dataGeneratorType: .random)
struct Follower {
  let username: String
  var avatarUrl: String?
}
```

I encounter the following error: 'Failed to receive a result from the plugin (from the macro 'SampleBuilder')'.

**Comment by pitt500** [comment]
Hi @nadavbarlev , thanks for reporting this issue. Currently I got sick but I will take a look in a couple of days. 

Feel free to send a PR if you find the issue yourself 👍

Regards,
Pitt

**Comment by pitt500** [comment]
Thank you for your feedback @nadavbarlev. The issue was fixed and SampleBuilder now supports Optionals! 🚀
