### ISSUE TITLE
Type X has no member sample

### ISSUE THREAD

**Issue by EmirhanKarahan** [pitt500/SwiftAndTipsMacros#5]
After adding "SampleBuilder", even expanding macro sample is shown but IDE gives error of has no member.

![Screenshot 2024-06-25 at 09 57 30](https://github.com/pitt500/SwiftAndTipsMacros/assets/48404459/741d5735-4916-48dc-845e-5e9a6af64f6a)

Device Specs:
Xcode 15.4
M3 Pro - MacOS Sonoma

**Comment by pitt500** [comment]
Hi @EmirhanKarahan, thanks for posting the issue.

![SampleBuilder UIKit](https://github.com/pitt500/SwiftAndTipsMacros/assets/17436242/d2a7c1f4-ad74-488b-ac57-d79c14f55c8f)

I tried to replicate the same issue you posted, but everything works fine on my machine.

Did you try cleaning build folder and removing derived data?

I ran it in Xcode 15.4 and Xcode 16 beta.

Regards,
Pitt

**Comment by EmirhanKarahan** [comment]
I was hundred percent sure that I have removed derived data and build folder but It seems I didn't. :D It works now. Thank you for your time.
